services:
  store-0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8060:8060"
    depends_on:
      - store-1
      - store-2

  store-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-1
    ports:
      - "8081:8081"
      - "8071:8071"
      - "8061:8061"

  store-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-2
    ports:
      - "8082:8082"
      - "8072:8072"
      - "8062:8062"

networks:
  default:
    name: datastore
