services:
  datastore-0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config
    ports:
      - "8080:8080"
      - "8070:8070"
    depends_on:
      - datastore-1
      - datastore-2

  datastore-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-1
    ports:
      - "8081:8081"
      - "8071:8071"

  datastore-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-2
    ports:
      - "8082:8082"
      - "8072:8072"

networks:
  default:
    name: datastore-network
