services:
  datastore-0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  datastore-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"

  datastore-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"

networks:
  default:
    name: datastore-network
